### ISSUE TITLE
Allow HTML to be rendered in sidebar description

### ISSUE THREAD

**Issue by jcoffa** [lukeorth/poison#123]
This would allow links and line-breaks to be used:

```toml
[params]
description = 'A portfolio for <a href="https://www.my-company.com">work</a><br>A tech blog for fun'
```

Which would render like:

![image](https://github.com/lukeorth/poison/assets/35551680/0c4b81c1-958c-4648-a047-c4df63280852)

I believe the change could be small as well; the description can be piped into the `safeHTML` function inside `layouts/sidebar/title.html` like so:

```html
<div class="sidebar-about">

    <!-- ... -->

    <p class="lead">
    {{ with .Site.Params.description }}{{. | safeHTML}}{{end}}
    <!--                                   ^^^^^^^^^^ new change -->
    </p>
</div>
```
