### ISSUE TITLE
Documentation for hideToc update and wider page

### ISSUE THREAD

**Issue by t3kg33k** [lukeorth/poison#179]
Your documentation states the following:

> Table of contents
> 
> Provide a floating table of contents for readers with large enough screens (i.e. screen-width > 1600 pixels).
> 
> If you prefer not to display a table of contents, you can disable them site-wide in your config.toml file.

```
[params]
    hideToc: true
```

However, it should be updated as such:

`hideToc = true`

Also, I was under the impression that if I hid the Table of Contents that are in the right sidebar it would make the mid-section of my page where all my content (post) exist would widen the page. Is this not so? If not, how do I widen the mid-section? My assumption is that it is in the CSS, right?

**Comment by Karta775** [comment]
For the second part of your issue, I found the following to work well enough for me:
```css
.content {
  min-width: 0rem;
  max-width: 100%;
  padding-left:  2rem;
  padding-right: 2rem;
  margin-left: 0rem;
  margin-right: 0rem;
  display: flex;
  flex-direction: column;
  flex-flow: column;
}

.post {
  max-width: 50rem; /* fine tune for the content width you want */
  min-width: 0rem;
}

.entries {
  max-width: 50rem; /* fine tune for the content width you want */
  min-width: 0rem;
}
```

Add these lines to your `assets/css/custom.css` and the content will fill the page as expected. If you want the post text to literally fill the width (I don't recommend it), you can use the following instead:
```css
.content {
  max-width: 100%;
  padding-left:  2rem;
  padding-right: 2rem;
  margin-left: 0rem;
  margin-right: 0rem;
}
```

Note that these code snippets only work nicely when `hideToc = true`. A better solution is needed for this to work with `hideToc = false`, but this suits my needs.
