### ISSUE TITLE
Copy button scrolls with content

### ISSUE THREAD

**Issue by minhperry** [lukeorth/poison#203]
View on load:

![image](https://github.com/user-attachments/assets/806d4411-ccd4-4710-84c8-293cbb5dd5c8)

On scroll:

![image](https://github.com/user-attachments/assets/47ab00f3-f840-441a-8133-a2f4f4435adc)

This doesn't apply for content with no scroll, well, because there are no scroll so the position is fixed.

I have tried to overwrite with this CSS, then the button will not scroll with content.

```css
.copy-button, .copy-success {
    position: sticky;
    margin-left: auto;
}

.code-container {
    display: flex; // or inline-flex works too.
}
```
However the .copy-success will just simply disappear if the container is scrollable. It is still in DOM, just that the svg is somehow not rendered (size is 8 x 24 in that case)
