### ISSUE TITLE
Sidebar: Nothing other than Posts and Projects is visible

### ISSUE THREAD

**Issue by rohitk-singh** [lukeorth/poison#25]
Possible Clone of #6 

First of all, thanks for the great template @lukeorth! Very simple, minimalist and elegant!

# Issue:
Can't enable anything other than `Posts` and `Projects` in the sidebar.  Specially, wanted to enable `About` but it doesn't work.

**Screenshot**:
![image](https://user-images.githubusercontent.com/1108318/215966081-e6d98121-bd4a-48ed-923b-0953e2a59082.png)

**Current Directory Structure**:
```
>> tree
.
├── about
│   └── about.md
├── posts
│   ├── hello-world.md
│   └── reset.md
├── projects
│   ├── project-1.md
│   ├── project-2.md
│   └── project-3.md
└── test
    ├── test-1.md
    └── test.md
```

**Current config.toml file**
```toml
baseURL = 'https://localhost'
languageCode = 'en-us'
title = 'Hugo'
theme = 'poison'

[params]
    brand = "Testing Hugo"                    # name of your site - appears in the sidebar
    description = "Random Thoughts"
    dark_mode = false                    # optional - defaults to false

    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Projects", URL = "/projects/"},
        {Name = "Test", URL = "/test/"},
    ]

```

# Experiment 1:
Adding "About" using different name for "project" works (see 5th line entry in menu items below). But, notice `Test` still doesn't show up.

![image](https://user-images.githubusercontent.com/1108318/215966977-a5da26b0-5fe9-4bf9-b11e-fc2f649ac1cc.png)

```
    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Projects", URL = "/projects/"},
        {Name = "Test", URL = "/test/"},
        {Name = "About", URL = "/projects/", HasChildren = false},
    ]
```

# Experiment 2: Enable Hugo Template Debugging

**Print sections**: code modified in `menu.html`
![image](https://user-images.githubusercontent.com/1108318/215968235-8d014a38-8b49-41b1-bbf1-662bc776414c.png)

**Result**:
![image](https://user-images.githubusercontent.com/1108318/215968289-0ace103d-665c-4195-a3a6-d68c7d5b9dd9.png)

**Whoa**, why is it appending "**s**" to the section names? Like "**`Abouts`**", "**`Tests`**" etc? This seems to be an issue.

If we update menu item URLs with "**abouts**" and "**tests**" then this finally displays the items.
```
    menu = [
        {Name = "About", URL = "/abouts/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Projects", URL = "/projects/"},
        {Name = "Test", URL = "/tests/"},
    ]
```
![image](https://user-images.githubusercontent.com/1108318/215969280-c03815c4-11a4-4bcd-9ad8-9cda8e60b83f.png)
